# Generated by Django 4.0.5 on 2022-06-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('CollectionID', models.AutoField(primary_key=True, serialize=False)),
                ('CollectionDate', models.DateField()),
                ('Type', models.CharField(max_length=100)),
                ('TotalWeight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('TotalCost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('CollectionPhoto', models.FileField(upload_to='uploads/collectionphoto')),
                ('CollectionSpreadsheet', models.FileField(upload_to='uploads/collectionspreadsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('DonorID', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Address1', models.CharField(max_length=500)),
                ('Address2', models.CharField(max_length=500)),
                ('PostCode', models.CharField(max_length=100)),
                ('DonorType', models.CharField(max_length=100)),
                ('Notes', models.CharField(max_length=1000)),
                ('Phone', models.CharField(max_length=500)),
                ('AddEmail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Wholesale',
            fields=[
                ('WholesaleID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalDonated', models.DecimalField(decimal_places=2, max_digits=6)),
                ('TotalSpent', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Remainder', models.DecimalField(decimal_places=2, max_digits=6)),
                ('CollectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodbankApp.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('ParticipationID', models.AutoField(primary_key=True, serialize=False)),
                ('Participation', models.BooleanField()),
                ('DonationType', models.CharField(max_length=100)),
                ('TotalDonated', models.DecimalField(decimal_places=2, max_digits=6)),
                ('CollectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodbankApp.collection')),
                ('DonorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodbankApp.donor')),
                ('WholesaleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodbankApp.wholesale')),
            ],
        ),
    ]
