# Generated by Django 4.0.5 on 2022-06-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodbankApp', '0002_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='AddEmail',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='donor',
            name='Email',
            field=models.CharField(max_length=254),
        ),
    ]
