# Generated by Django 4.0.5 on 2022-07-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodbankApp', '0003_alter_donor_addemail_alter_donor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='CollectionPhoto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='CollectionSpreadsheet',
            field=models.CharField(max_length=100),
        ),
    ]
