# Generated by Django 4.0.5 on 2022-08-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodbankApp', '0004_alter_collection_collectionphoto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.AlterField(
            model_name='participation',
            name='DonorID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FoodbankApp.donor'),
        ),
    ]
