# Generated by Django 4.0.5 on 2022-08-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodbankApp', '0005_delete_departments_alter_participation_donorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='WholesaleID',
            field=models.CharField(max_length=100),
        ),
    ]
