# Generated by Django 4.0.5 on 2022-08-22 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodbankApp', '0006_alter_participation_wholesaleid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='DonorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodbankApp.donor'),
        ),
    ]
