# Generated by Django 4.0.5 on 2022-08-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodbankApp', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
