# Generated by Django 4.0.5 on 2022-09-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodbankApp', '0009_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='AddEmail',
        ),
        migrations.AddField(
            model_name='donor',
            name='InvolveNo',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wholesale',
            name='WholesaleReceipt',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='participation',
            name='WholesaleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodbankApp.wholesale'),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='Remainder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='TotalDonated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='wholesale',
            name='TotalSpent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
