# Generated by Django 4.0.5 on 2022-10-03 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodbankApp', '0010_remove_donor_addemail_donor_involveno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='DropOffTime',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
