# Generated by Django 4.0.5 on 2022-10-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodbankApp', '0011_participation_dropofftime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='Participation',
            new_name='PaymentRecieved',
        ),
    ]
