# Generated by Django 4.1.2 on 2022-10-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FoodbankApp", "0012_rename_participation_participation_paymentrecieved")
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="CollectionStatus",
            field=models.CharField(default="PLANNED", max_length=100),
        ),
        migrations.AlterField(
            model_name="participation",
            name="DonationType",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AlterField(
            model_name="participation",
            name="PaymentRecieved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="participation",
            name="TotalDonated",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
