# Generated by Django 4.1.2 on 2022-10-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("FoodbankApp", "0013_collection_collectionstatus_and_more")]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="Address1",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="Address2",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="DonorType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="Notes",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="Phone",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="donor",
            name="PostCode",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
