# Generated by Django 4.1.2 on 2022-11-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FoodbankApp", "0014_alter_donor_address1_alter_donor_address2_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="DropOffTime",
            field=models.CharField(default="N/A", max_length=100),
        )
    ]
