# Generated by Django 4.1.2 on 2022-11-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("FoodbankApp", "0015_alter_participation_dropofftime")]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="Notes",
            field=models.CharField(blank=True, max_length=1000, null=True),
        )
    ]
