# Generated by Django 4.1.2 on 2023-01-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("FoodbankApp", "0016_participation_notes")]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="TotalCost",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        )
    ]
