# Generated by Django 4.1.2 on 2023-01-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("FoodbankApp", "0017_alter_collection_totalcost")]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="Address3",
            field=models.CharField(blank=True, max_length=500, null=True),
        )
    ]
