# Generated by Django 4.1.2 on 2023-02-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("FoodbankApp", "0019_wholesale_notes")]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="PostCode",
            field=models.CharField(blank=True, max_length=12, null=True),
        )
    ]
